package Formularios;

import java.awt.CardLayout;
import java.awt.Color;
import java.net.URL;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author José Pérez
 */
public class Portal extends javax.swing.JFrame {

//    Panel_Reportes Reporte = new Panel_Reportes();
    Panel_Viajes Viajes = new Panel_Viajes();
    Panel_Chofer Chofer = new Panel_Chofer();
    Panel_Clientes Clientes = new Panel_Clientes();
    CardLayout vistac;

    public Portal() {
        initComponents();
        setLocationRelativeTo(null);
        icon_Formulario();
//        setExtendedState(MAXIMIZED_BOTH);
        vistac = (CardLayout) pnl_vista_principal.getLayout();
        FechaActual();
        run();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        LblNombreP = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        BtnRegistrar = new javax.swing.JButton();
        BtnClientes = new javax.swing.JToggleButton();
        jLabel6 = new javax.swing.JLabel();
        BtnChofer = new javax.swing.JToggleButton();
        BtnViajes = new javax.swing.JToggleButton();
        BtnaDesconectar = new javax.swing.JButton();
        pnl_vista_principal = new javax.swing.JPanel();
        JHora = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JFecha = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Portal La Barrera");
        setModalExclusionType(null);

        jLabel1.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        jLabel1.setText("Bienvenido : ");

        LblNombreP.setFont(new java.awt.Font("OCR A Extended", 1, 14)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        BtnRegistrar.setText("Registrar ");
        BtnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistrarActionPerformed(evt);
            }
        });
        BtnRegistrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                BtnRegistrarKeyReleased(evt);
            }
        });

        BtnClientes.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BtnClientes.setText("Alta de Clientes");
        BtnClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnClientesMouseClicked(evt);
            }
        });
        BtnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnClientesActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/LogoPortal.jpg"))); // NOI18N

        BtnChofer.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BtnChofer.setText("Choferes / Vehiculos");
        BtnChofer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnChoferActionPerformed(evt);
            }
        });

        BtnViajes.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BtnViajes.setText("Viajes");
        BtnViajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnViajesActionPerformed(evt);
            }
        });

        BtnaDesconectar.setText("Desconectar");
        BtnaDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnaDesconectarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 7, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnChofer, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnViajes, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnaDesconectar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(BtnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(BtnChofer, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(BtnViajes, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addComponent(BtnRegistrar)
                .addGap(18, 18, 18)
                .addComponent(BtnaDesconectar)
                .addGap(18, 18, 18)
                .addComponent(jButton1))
        );

        pnl_vista_principal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnl_vista_principal.setLayout(new java.awt.CardLayout());

        JHora.setFont(new java.awt.Font("OCR A Extended", 1, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        jLabel2.setText("Hora: ");

        jLabel3.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        jLabel3.setText("Fecha: ");

        JFecha.setFont(new java.awt.Font("OCR A Extended", 1, 14)); // NOI18N

        jLabel5.setBackground(new java.awt.Color(204, 0, 0));
        jLabel5.setFont(new java.awt.Font("OCR A Extended", 1, 12)); // NOI18N
        jLabel5.setText("Remises LA BARRERA   ");

        jLabel4.setFont(new java.awt.Font("OCR A Extended", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("Version 1.1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LblNombreP, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JHora, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 205, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnl_vista_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_vista_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(LblNombreP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(JHora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(1346, 846));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistrarActionPerformed

        RegistroUsuarios ventana = new RegistroUsuarios();
        ventana.setVisible(true);


    }//GEN-LAST:event_BtnRegistrarActionPerformed
    public void icon_Formulario() {
        //aca debemos importar la imagen de nuestra libreria 

        URL url = getClass().getResource("/image/icono.png");
        //Instanciamos ... 
        ImageIcon icon_Formulario = new ImageIcon(url);
        setIconImage(icon_Formulario.getImage());
    }

    public void FechaActual() { //Metodo para mostara la fecha 

        LocalDateTime ahora = LocalDateTime.now();
        int año = ahora.getYear();
        int mes = ahora.getMonthValue();
        int dia = ahora.getDayOfMonth();

        JFecha.setText(dia + "/" + mes + "/" + año);
    }

    public void run() { //Metodo con hilos para actualizar la hora
        DateTimeFormatter formateador = DateTimeFormatter.ofPattern("HH:mm:ss");
        Runnable runnable = () -> {
            while (true) {
                try {
                    Thread.sleep(500);
                    JHora.setText(formateador.format(LocalDateTime.now()));
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
            }
        };
        Thread hilo = new Thread(runnable);
        hilo.start();

    }


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void BtnRegistrarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnRegistrarKeyReleased
        //        String busqueda_usuario = Met.BuscarUsuarioRegistrado(TxtCorre.getText(), contraseña) , TxtContraseña.getText());


    }//GEN-LAST:event_BtnRegistrarKeyReleased

    private void BtnChoferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnChoferActionPerformed
        if (BtnChofer.isSelected()) {

            pnl_vista_principal.add(Chofer, "Chofer");
            vistac.show(pnl_vista_principal, "Chofer");
            SwingUtilities.updateComponentTreeUI(this);
            this.repaint();
            //ACTIVAMOS EL BOTON QUE PRESIONAMOS Y BLOQUEAMOS LOS DEMAS
            BtnClientes.setEnabled(false);

//            BtnReportes.setEnabled(false);
            BtnViajes.setEnabled(false);

            BtnChofer.setBackground(Color.WHITE);

        } else {
            //LIMPIAMOS LAS CAJAS DE LO CONTRARIO
            pnl_vista_principal.removeAll();
            SwingUtilities.updateComponentTreeUI(this);
            this.repaint();
            //Y ACTIVAMOS NUEVAMENTES LOS BOTONES Y DEVOLVEMOS EL COLOR AL BOTON 
            BtnClientes.setEnabled(true);
//            BtnReportes.setEnabled(true);

            BtnViajes.setEnabled(true);
            BtnChofer.setBackground(new Color(204, 204, 204));

        }
    }//GEN-LAST:event_BtnChoferActionPerformed

    private void BtnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnClientesActionPerformed

        if (BtnClientes.isSelected()) {

            pnl_vista_principal.add(Clientes, "Clientes");
            vistac.show(pnl_vista_principal, "Clientes");
            SwingUtilities.updateComponentTreeUI(this);
            this.repaint();
            //ACTIVAMOS EL BOTON QUE PRESIONAMOS Y BLOQUEAMOS LOS DEMAS
            BtnChofer.setEnabled(false);

//            BtnReportes.setEnabled(false);
            BtnViajes.setEnabled(false);

            BtnClientes.setBackground(Color.WHITE);

        } else {
            //LIMPIAMOS LAS CAJAS DE LO CONTRARIO
            pnl_vista_principal.removeAll();
            SwingUtilities.updateComponentTreeUI(this);
            this.repaint();
            //Y ACTIVAMOS NUEVAMENTES LOS BOTONES Y DEVOLVEMOS EL COLOR AL BOTON 
            BtnChofer.setEnabled(true);
//            BtnReportes.setEnabled(true);

            BtnViajes.setEnabled(true);
            BtnClientes.setBackground(new Color(204, 204, 204));

        }


    }//GEN-LAST:event_BtnClientesActionPerformed

    private void BtnClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnClientesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnClientesMouseClicked

    private void BtnViajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnViajesActionPerformed
        if (BtnViajes.isSelected()) {

            pnl_vista_principal.add(Viajes, "Viajes");
            vistac.show(pnl_vista_principal, "Viajes");
            SwingUtilities.updateComponentTreeUI(this);
            this.repaint();
            //ACTIVAMOS EL BOTON QUE PRESIONAMOS Y BLOQUEAMOS LOS DEMAS
            BtnChofer.setEnabled(false);

//            BtnReportes.setEnabled(false);
            BtnClientes.setEnabled(false);

            BtnViajes.setBackground(Color.WHITE);

        } else {
            //LIMPIAMOS LAS CAJAS DE LO CONTRARIO
            pnl_vista_principal.removeAll();
            SwingUtilities.updateComponentTreeUI(this);
            this.repaint();
            //Y ACTIVAMOS NUEVAMENTES LOS BOTONES Y DEVOLVEMOS EL COLOR AL BOTON 
            BtnChofer.setEnabled(true);
//            BtnReportes.setEnabled(true);

            BtnClientes.setEnabled(true);
            BtnViajes.setBackground(new Color(204, 204, 204));

        }
    }//GEN-LAST:event_BtnViajesActionPerformed

    private void BtnaDesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnaDesconectarActionPerformed
        String eti;
        eti = LblNombreP.getText();
        JOptionPane.showMessageDialog(rootPane, "" + eti + " se desconecto del sistema!");
        InicioSesion ventana = new InicioSesion();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnaDesconectarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Portal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Portal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Portal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Portal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Portal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BtnChofer;
    private javax.swing.JToggleButton BtnClientes;
    public javax.swing.JButton BtnRegistrar;
    private javax.swing.JToggleButton BtnViajes;
    private javax.swing.JButton BtnaDesconectar;
    private javax.swing.JLabel JFecha;
    private javax.swing.JLabel JHora;
    public static javax.swing.JLabel LblNombreP;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnl_vista_principal;
    // End of variables declaration//GEN-END:variables
}
